services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

      # socket docker (double)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/docker.sock:/run/docker.sock:ro

    command:
      - "--docker=unix:///var/run/docker.sock"
      - "--docker_only=true"
      - "--housekeeping_interval=10s"
