services:
  node_exporter:
    image: prom/node-exporter:v1.8.2
    pid: host
    command:
      - "--path.rootfs=/host"
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    restart: unless-stopped
