services:
  samba:
    image: dperson/samba
    container_name: samba
    env_file: 
        - /etc/portainer-env/dl-samba.env  
    ports:
      - "445:445"
    volumes:
      - /srv/downloads/qbittorrent/downloads:/downloads
    command: >
      -u "${SAMBA_USER};${SAMBA_PASS}"
      -s "downloads;/downloads;yes;no;no;${SAMBA_USER}"
    restart: unless-stopped